### ISSUE TITLE
function' object has no attribute 'im_self

### ISSUE THREAD

**Issue by nordbit** [jazzband/django-ddp#18]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/js/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/srv/js/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/srv/js/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/js/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/srv/js/lib/python3.4/site-packages/dddp/apps.py", line 31, in ready
    self.api = autodiscover()
  File "/srv/js/lib/python3.4/site-packages/dddp/__init__.py", line 137, in autodiscover
    autodiscover_modules('ddp', register_to=API)
  File "/srv/js/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/opt/py3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/srv/js/lib/python3.4/site-packages/dddp/ddp.py", line 24, in <module>
    API.register([Logs])
  File "/srv/js/lib/python3.4/site-packages/dddp/api.py", line 796, in register
    self.clear_api_path_map_cache()
  File "/srv/js/lib/python3.4/site-packages/dddp/api.py", line 206, in clear_api_path_map_cache
    if api_provider.clear_api_path_map_cache.im_self is not None:
AttributeError: 'function' object has no attribute 'im_self'

```

Python == 3.4.3, Django == 1.8.5,  gevent == 1.1b7.dev0

**Comment by tysonclugg** [comment]
@nordbit -- Please test django-ddp==0.17.2 and open a new ticket / re-open this ticket as appropriate if you encounter any issues.
