### ISSUE TITLE
dddp.AlreadyRegistered: API with prefix '/' is already registered to <dddp.ddp.Logs object at 0x7fd5d1a2d4a8>

### ISSUE THREAD

**Issue by Kannaj** [jazzband/django-ddp#19]
Hello, 

Got an issue when i'm using gevent 1.1b6 (python3.4 and django 1.8)

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/dddp/apps.py", line 31, in ready
    self.api = autodiscover()
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/dddp/__init__.py", line 137, in autodiscover
    autodiscover_modules('ddp', register_to=API)
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/dddp/accounts/ddp.py", line 568, in <module>
    API.register([Users, LoginServiceConfiguration, LoggedInUser, Auth])
  File "/home/kj/.virtualenvs/freelance/lib/python3.4/site-packages/dddp/api.py", line 792, in register
    self._registry[api.api_path_prefix],
dddp.AlreadyRegistered: API with prefix '/' is already registered to <dddp.ddp.Logs object at 0x7fd5d1a2d4a8>
```

**Comment by tysonclugg** [comment]
@Kannaj -- Please test django-ddp==0.17.2 and open a new ticket / re-open this ticket as appropriate if you encounter any issues.
