### ISSUE TITLE
Current gevent version not supported

### ISSUE THREAD

**Issue by Kannaj** [jazzband/django-ddp#20]
Hi,

Getting the below error when attempting to migrate the database.

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/dddp/__init__.py", line 5, in <module>
    from gevent.local import local
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/gevent/hub.py", line 289
    except Exception, ex:
```

<b>The requirements.txt file still installs gevent 1.0.2. Should it be gevent 1.1b7?</b>

<b>I tried installing gevent 1.1b7 and after some minor tweaks to the django model (for the to-do example) - I get the below error: </b>

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/dddp/apps.py", line 31, in ready
    self.api = autodiscover()
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/dddp/__init__.py", line 141, in autodiscover
    autodiscover_modules('ddp', register_to=API)
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/kj/Desktop/django-meteor/todo/django_todos/ddp.py", line 16, in <module>
    Tasks,
  File "/home/kj/.virtualenvs/meteor-django/lib/python3.4/site-packages/dddp/api.py", line 787, in register
    if api.api_path_prefix in self._registry:
AttributeError: 'Task1' object has no attribute 'api_path_prefix'
```

**Comment by tysonclugg** [comment]
Hi @Kannaj - the [PyPy feature branch](https://github.com/commoncode/django-ddp/tree/feature/%2316_PyPy_support) has platform specific install requirements that will be useful in solving this, I'll see what I can do to apply this technique for you today.
